version: '3.7'
services:
  flask:
    build:
      context: ./
    ports:
      - "5000:5000"
    volumes:
      - .:/my_app
    depends_on:
      - "elasticsearch"
    command: >
      bash -c "./wait-elastic.sh && python3 load_data.py && python3 app.py"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    ports:
      - "5601:5601"
    environment:
      - discovery.type=single-node
    depends_on:
      - elasticsearch
